// _________________________________________________________________________
//
//  © Hi-Integrity Systems 2012. All rights reserved.
//  www.hisystems.com.au - Toby Wicks
// 
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//	    http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// _________________________________________________________________________
//

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DatabaseObjects.SQL.Serializers
{
	internal class HyperSqlSerializer : Serializer
	{
		public override Database.ConnectionType Type
		{
			get 
			{ 
				return Database.ConnectionType.HyperSQL; 
			}
		}

		public override string SerializeViewExists(SQLViewExists viewExists)
		{
			var select = new SQLSelect();

			select.Tables.Add("VIEWS").SchemaName = "INFORMATION_SCHEMA";
			select.Where.Add("TABLE_SCHEMA", ComparisonOperator.EqualTo, "PUBLIC");
			select.Where.Add("TABLE_NAME", ComparisonOperator.EqualTo, viewExists.ViewName);

			return SerializeSelect(select);
		}

		public override string SerializeRollbackTransaction(SQLRollbackTransaction rollbackTransaction)
		{
			return "ROLLBACK";
		}

		public override string SerializeCommitTransaction(SQLCommitTransaction commitTransaction)
		{
			return "COMMIT";
		}

		public override string SerializeBeingTransaction(SQLBeginTransaction beginTransaction)
		{
			return "START TRANSACTION";
		}

		public override string SerializeTableExists(SQLTableExists tableExists)
		{
			var select = new SQLSelect();
			select.Tables.Add("SYSTEM_TABLES").SchemaName = "INFORMATION_SCHEMA";
			select.Where.Add("TABLE_SCHEM", ComparisonOperator.EqualTo, "PUBLIC");
			select.Where.Add("TABLE_NAME", ComparisonOperator.EqualTo, tableExists.Name);

			return SerializeSelect(select);
		}

		public override string SerializeIdentifier(string strIdentifierName)
		{
			return "\"" + strIdentifierName + "\"";
		}

		public override string SerializeByteArray(byte[] data)
		{
			return SerializeByteArray("x'", data, "'");
		}

		public override string SerializeAutoIncrementValue(SQLAutoIncrementValue autoIncrementValue)
		{
			return "SELECT IDENTITY() AS " + SerializeIdentifier(autoIncrementValue.ReturnFieldName);
		}

		public override string SerializeTableFieldDataType(SQLTableField field)
		{
			if (field.AutoIncrements)
				return base.SerializeTableFieldDataType(field) + " GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1)";
			else
				return base.SerializeTableFieldDataType(field);
		}

		public override string SerializeDataType(SQL.DataType dataType, int size, int precision, int scale)
		{
			switch (dataType)
			{
				case DataType.TinyInteger:
					return "TINYINT";
				case DataType.SmallInteger:
					return "SMALLINT";
				case DataType.Integer:
					return "INT";
				case DataType.BigInteger:
					return "BIGINT";
				case DataType.Character:
					return "CHAR(" + size.ToString() + ")";
				case DataType.UnicodeCharacter:
					return "CHAR(" + size.ToString() + ")";
				case DataType.VariableCharacter:
					return "VARCHAR(" + size.ToString() + ")";
				case DataType.UnicodeVariableCharacter:
					return "VARCHAR(" + size.ToString() + ")";
				case DataType.Decimal:
					return "NUMBER(" + precision.ToString() + "," + scale.ToString() + ")";
				case DataType.Real:
					return "DOUBLE";
				case DataType.Float:
					return "DOUBLE";
				case DataType.SmallMoney:
					return "NUMBER(10,4)";
				case DataType.Money:
					return "NUMBER(19,4)";
				case DataType.Boolean:
					return "BOOLEAN";
				case DataType.SmallDateTime:
					return "DATE";
				case DataType.DateTime:
					return "DATE";
				case DataType.TimeStamp:
					return "TIMESTAMP";
				case DataType.Text:
					return "CLOB(2G)";
				case DataType.UnicodeText:
					return "CLOB(2G)";
				case DataType.Binary:
					return "BINARY(8000)";
				case DataType.VariableBinary:
					return "VARBINARY(8000)";
				case DataType.Image:
					return "BLOB(2G)";
				case DataType.UniqueIdentifier:
					return "UNIQUEIDENTIFIER";
			}

			return base.SerializeDataType(dataType, size, precision, scale);
		}
	}
}
